### ISSUE TITLE
Missing SOLR_HOST in settings.py

### ISSUE THREAD

**Issue by pillows** [canvasnetworks/canvas#4]
This has been discussed already with Timothy but I wanted to post this here for archival purposes. Or heck if someone solves it before us.

```
AttributeError: 'Settings' object has no attribute 'SOLR_HOST'
```

So this is what I have before I mess up the settings.py file
After adding a SOLR_HOST variable:

```
SOLR_HOST = 'http://192.168.23.128:8983/solr' #Dev VM
```

I get:

```
solr.core.SolrException: HTTP code=502, reason=Bad Gateway
```

So at this point I pretty much know it's my error. But I'm just logging my progress.

**Comment by TimothyFitz** [comment]
Yeah, Bad Gateway most likely means Jetty started but SOLR did not. Maybe a SOLR config issue, or version or classpath issue.

**Comment by pillows** [comment]
I believe I fixed the issue. But it involves tweaking the code a bit, which I don't like doing because it could mess up the app.

I will make a PR with the solutions. But even fixing the SOLR_HOST issue there's another problem which I'll mention in another issue.

canvas/website/settings.py (Insert on any line by itself):
SOLR_HOST = 'http://[INSERT IP/DOMAIN HERE]:8983/solr'

canvas/website/canvas/search.py (line 19)
return solr.Solr(settings.SOLR_HOST)

On line 19 of search.py, self.core comes out as "group". Not sure what the purpose of that was though.
