### ISSUE TITLE
Login fails with correct credentials

### ISSUE THREAD

**Issue by pillows** [canvasnetworks/canvas#9]
I'm not sure what much I can about this issue. I used the same credentials from when I registered. I've attempted this multiple times to not avail. 

(Oh when I mean when I registered, I mean a brand new registration)

The login code is from website/canvas/views.py
The issue is caught from the first if statement on line 414

**Comment by aehlke** [comment]
Hi Pillows,

Sorry but all that's been open sourced in this project is the source code and static assets, but none of the original user data. You'll have to create a new account to play with Canvas again.
